### ISSUE TITLE
Can I update webmin directly ?

### ISSUE THREAD

**Issue by MX10-AC2N** [YunoHost-Apps/webmin_ynh#12]
Hello, when I am connected to my webmin server, I have an update offered to me but nothing in the updates via yunohost admin ..
Can we update? Or should we wait for an update via yunohost ..?
Thank you.

**Comment by merchmanager** [comment]
"Webmin will update itself when system updates are run. So no need to run upgrade script once installed."
found this in documentation at
https://github.com/YunoHost-Apps/webmin_ynh/blob/master/README.md

**Comment by MX10-AC2N** [comment]
OK thank @merchmanager
