### ISSUE TITLE
Not able to use the app

### ISSUE THREAD

**Issue by hovancik** [YunoHost-Apps/webmin_ynh#22]
### Describe the bug

Not being able to use the app due to not being able to login.

### Context

- Hardware: Raspberry Pi
- YunoHost version: 4.3.6.2
- I have access to my server: Through SSH | through the webadmin | direct access via keyboard / screen
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using, or trying to install package version/branch: 1.984~ynh1

### Steps to reproduce
- install app via YNH Admin on `xxxx.noho.st`
- set domain as `wm.xxxx.noho.st`
- set myself as the admin of the app
- wait for install to finish https://paste.yunohost.org/raw/tilavabenu
- login as User to `xxxx.noho.st`
- click on Webmin app
- try login as User with name/password
- no luck :( 
```
 Warning!
Login failed. Please try again.
```

### Expected behavior

I am able to login with my YNH user

**Comment by collector-ynh** [comment]
I have exactly the same problem. Unable to connect.Apparently this bug has still not been fixed.

**Comment by hovancik** [comment]
This is not fixed for me. Still having the same issue. 

> Only user given permission at time of the installation can access the Webmin login interface
> To login to webmin, use root and root password

What does this mean? It seems to say opposite things. What's the login process? I am not able to login with both Admin and User login.

**Comment by MohamedElashri** [comment]
You should log to webmin using actual root user (on Linux server itself) not your yunohost user. 
So probably you installed yunohost itself with `root` then you can log in with this user. 

If like anyone who use `root` or any admin user without password (ssh certificate access) you will need to follow this [document](http://doxfer.webmin.com/Webmin/WebminUsers) on how to grant password. In short, you can tell webmin the password using `changepass.pl` as follows. Then it will work as expected. 

```
sudo /usr/share/webmin/changepass.pl /etc/webmin root <your_password>
```
